/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stacksnow.flow.runner.spark.java;

import org.junit.Test;

public class FlowRunnerTest {

    @Test
    public void testStartDAG() throws Exception {
    }
}
