server:
  port: 9090

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url:  jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

lake:
  s3BucketName: mlops-lake

livy:
  url: http://host.docker.internal:8998

tasks:
  url: http://host.docker.internal:9090/tasks

jars:
  url: http://host.docker.internal:9090/jars

flows:
  url: http://host.docker.internal:9090/flows

processes:
  url: http://host.docker.internal:9090/processes

